// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.user_id", "82d49e86-b593-4458-9757-ec40808788f8");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1538465048);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1536654789);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1537255381);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1537255621);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1537255501);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1536655029);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1536654909);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 788480);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1536654282);
user_pref("browser.laterrun.bookkeeping.sessionCount", 3);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 69);
user_pref("browser.newtabpage.activity-stream.impressionId", "{0019d046-7595-48d0-8753-e104830e15ae}");
user_pref("browser.newtabpage.activity-stream.migrationExpired", true);
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1536649200);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 3);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.onboarding.notification.last-time-of-changing-tour-sec", 1536654293);
user_pref("browser.onboarding.seen-tourset-version", 2);
user_pref("browser.onboarding.tour-type", "new");
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 8);
user_pref("browser.rights.3.shown", true);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1537255364828");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1537257161828");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1537255365826");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1537258965826");
user_pref("browser.search.countryCode", "KR");
user_pref("browser.search.region", "KR");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20180913170256");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1538465022");
user_pref("browser.slowStartup.averageTime", 11649);
user_pref("browser.slowStartup.samples", 3);
user_pref("browser.startup.homepage_override.buildID", "20180913170256");
user_pref("browser.startup.homepage_override.mstone", "62.0");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\"],\"currentVersion\":14,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1536654310161");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "62.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("extensions.blocklist.lastModified", "Wed, 05 Sep 2018 22:34:28 GMT");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", -1);
user_pref("extensions.databaseSchema", 27);
user_pref("extensions.getAddons.cache.lastUpdate", 1538465048);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppBuildId", "20180913170256");
user_pref("extensions.lastAppVersion", "62.0");
user_pref("extensions.lastPlatformVersion", "62.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"directory\":\"{8c248489-6e04-42e0-81e2-d10d965dba39}\",\"addons\":{\"fxmonitor@mozilla.org\":{\"version\":\"2.3\"},\"telemetry-coverage-bug1487578@mozilla.org\":{\"version\":\"7.0\"}}}");
user_pref("extensions.webextensions.uuids", "{\"webcompat@mozilla.org\":\"ba3add6f-cd24-4f0b-a710-2b0f47e394d8\",\"screenshots@mozilla.org\":\"8b439612-3806-4c67-be37-eaa8e8a20a73\",\"fxmonitor@mozilla.org\":\"cedfaf9b-1ed2-4c5a-8c25-2180d40e7990\"}");
user_pref("idle.lastDailyNotification", 1537255415);
user_pref("lightweightThemes.usedThemes", "[]");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1536654352);
user_pref("media.gmp-gmpopenh264.version", "1.7.1");
user_pref("media.gmp-manager.buildID", "20180913170256");
user_pref("media.gmp-manager.lastCheck", 1537255377);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.initialized", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1536655853);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "37493169-3bfb-4681-a359-dab20abf9a5d");
user_pref("services.blocklist.addons.checked", 1536613471);
user_pref("services.blocklist.gfx.checked", 1536613471);
user_pref("services.blocklist.onecrl.checked", 1536613471);
user_pref("services.blocklist.pinning.checked", 1536613471);
user_pref("services.blocklist.plugins.checked", 1536613471);
user_pref("services.settings.clock_skew_seconds", 41318);
user_pref("services.settings.last_etag", "\"1536613417349\"");
user_pref("services.settings.last_update_seconds", 1536613471);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1536655853);
user_pref("toolkit.startup.last_success", 1538465014);
user_pref("toolkit.telemetry.cachedClientID", "b37552aa-c2da-4ff3-bb9a-47475c29ae81");
user_pref("toolkit.telemetry.previousBuildID", "20180913170256");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
